baseURL = "https://blog.dazzlog.de/"
languageCode = "en-us"
defaultContentLanguage = "en"

title = "DazzLog"

theme = "hugo-ficurinia"

author = "dazz"
copyright = "dazz - [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)."

pagination.pagerSize = 5
summaryLength = 70

[services]
    [services.googleAnalytics]
        id = 'G-SZG9LWH6KX'

[privacy]
#    [privacy.cactus]
#        disable = false
    [privacy.googleAnalytics]
        disable = false
        respectDoNotTrack = true

[params]
    description = "dazz blog about programming and other cool stuff"
    author = "dazz | Anne-Julia Seitz"
    logo = "/logo.svg"
    favicon = "/favicon.png"
    faviconIco = "/favicon.ico"
    appletouch = "/apple-touch-icon.png"
    svgicon = "/logo.svg"
    icon512 = "/android-chrome-512x512.png"

    # commento = "https://cloud.techpills.technology:54321/js/commento.js"
    cactusCommentsSiteName = "dazzlog"
    cactusCommentsServerName = "cactus.chat"
    cactusCommentsHomeserver = "https://matrix.cactus.chat:8448"

    imageInArticlePreview = true  # show images in article preview; default false
    fitImageInArticlePreview = false  # make article preview images fit the article preview instead of getting cropped
    articleSummary = true  # show a summary in article preview; default true

    enableShareOnFediverse = true
    tocBeforeImage = false  # show the table of contents before the main article image; default false

    # redirect to baseURL if current URL host doesn't match
    # useful if deploying in gitlab pages with custom domain and don't want
    # the username.gitlab.io/website url to persist
    # this requires you to set baseURL (see above)
    forceRedirect = false

    infiniteScrolling = false  # activates infinite scrolling instead of regular pagination
    enableFooterColumns = true  # activates footer columns, as described below
    enableJumbotron = false  # enables jumbotron, as described below
    # related articles will be selected randomly based on tags and shown at
    # the bottom of the article, after the comments
    enableRelatedArticles = true
    relatedArticlesNum = 2  # how many related articles to show
    randomRelated = false  # sorts related articles in random order (randomized at built time)

    contentWidth = "1000px"  # maximum width of the site content, css syntax

    # shows a specified single page as a home page, instead of the traditional articles list
    # requires setting `homeSinglePage`
    # goes well with extraContentDirs
    showSinglePageAsHome = false
    homeSinglePage = "/home"

    paperCards = true  # enable paper card style; default false
    buttonTags = false  # enable button tag style; default false
    tagsInArticlePreview = true  # enable tags list in the article preview card
    gridView = false  # show post list as a grid. goes well with paperCards
    bigArticleTitle = false  # makes the title in the single article view bigger
    navtype = "standard"  # changes the style of the pagination, available styles are: "standard", "circles"
    enableShadow = true  # shows a shadow around some elements
    menuStyle = "standard"  # changes the style of the main site navigation menu, available styles are: "standard", "buttons"

    enableSearch = true  # enable search page
    searchbarEverywhere = true  # if the searchbar should be shown in every page; requires enableSearch
    searchMenuLink = false  # add a search link to the navigation menu; requires enableSearch
    mobileHamburgerNav = true  # alternative hamburger menu layout for the main nav menu when screen is small

    enableFeatured = false  # enable a particular view for articles marked as featured (featured: true in the article frontmatter)

    underlineTitleLinks = false  # show an underline also for links that are titles

    # alternative sidebar layout
    enableSidebarLayout = false
    tocInSidebar = true  # if the sidebar is enbabled, show the TOC in the sidebar

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false
        lineNumbersInTable = false
        tabWidth = 4
        style = "dracula"
    [markup.tableOfContents]
        endLevel = 5
        ordered = false
        startLevel = 2

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 50
    [[menu.main]]
        identifier = "talks"
        name = "Talks"
        url = "/talks"
        weight = 40

    [[menu.icons]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/dazz"
        weight = 10
#    [[menu.icons]]
#        identifier = "gnome"
#        name = "GNOME GitLab"
#        url = "https://gitlab.gnome.org/gabmus"
#        weight = 20
#    [[menu.icons]]
#        identifier = "youtube"
#        name = "YouTube"
#        url = "https://youtube.com/TechPillsNet"
#        weight = 30
    [[menu.icons]]
        identifier = "mastodon"
        name = "Mastodon"
        url = "https://phpc.social/@dazz"
        weight = 40
